### ISSUE TITLE
Create Google Calendar for OWDDM events and link to the website

### ISSUE THREAD

**Issue by kinxiel** [owddm/owddm.github.io#163]
Similar to the RSS button on the Join Page, OWDDM currently does not have a Google Calendar that we can use to link events.

Help wanted to create a Google Calendar for OWWDM and link it to the Join Page.

**Comment by coliff** [comment]
You can subscribe to the OWDDM Events calendar from Meetup, maybe using that might be better to reduce duplication and avoid things getting out of sync? I subscribe to the OWDDM events calendar and everything shows for me in Google Calendar already. Links are at the bottom here:
https://www.meetup.com/osaka-web-designers-and-developers-meetup/events/calendar/

**Comment by martinheidegger** [comment]
We also have KWDDM now and it would be cool to have all events in one
system. Also it would be nice if we could move on from meetup.com at some
point in the far future

**Comment by kinxiel** [comment]
So should we have two links show up on the page? One for OWDDM Meetup and another for KWDDM?

**Comment by martinheidegger** [comment]
Hmm... having a filter may be nice, but first version with both together may be good.

**Comment by kinxiel** [comment]
Added the calendars for both OWDDM and KWDDM (although, the user needs to sign up or be signed up in Meetup.com).
