### ISSUE TITLE
Information button on the photos page extends passed the container (on mobile)

### ISSUE THREAD

**Issue by kinxiel** [owddm/owddm.github.io#176]
Will need to adjust the CSS slightly.

![owddm_screenshot](https://github.com/owddm/owddm.github.io/assets/11483654/86d730fc-c79e-4ba8-bde5-737f7123529b)

**Comment by martinheidegger** [comment]
It is not a problem of the container but the of the photos, they reach over the right border and probably need a max-width

**Comment by kinxiel** [comment]
Ok I'll take a look at it later.

**Comment by jamcgrath** [comment]
I fixed it.
