### ISSUE TITLE
Caching Problems

### ISSUE THREAD

**Issue by martinheidegger** [owddm/owddm.github.io#178]
The current way how the website is deployed (static site on github with data source in /public) is not refreshing correctly on the website, sometimes new events flash up on the events page as well as new images. We need to change the deployment system.

**Comment by kinxiel** [comment]
Maybe we should move to purely client side fetching.

**Comment by martinheidegger** [comment]
Client side fetching would break the event links and it would be kind of
good to keep the links. Maybe remove the client side script?

**Comment by kinxiel** [comment]
You mean completely build it as pure static site?

**Comment by coliff** [comment]
not sure what the exact problem is (haven't encountered any issues while browsing the site on my PC, Mac, iPad or iPhone) but could caching issues be resolved at the Cloudflare level? I don't quite understand why the 'deployment system' would need to be changed.

**Comment by kinxiel** [comment]
I also have not on Mac and iOS using Vivaldi, Chrome and Safari, but can imagine this kind of thing happening. What browser did you find this issue on?

**Comment by kinxiel** [comment]
Is this what you mean?

![image](https://github.com/owddm/owddm.github.io/assets/11483654/583392ff-afc0-41ef-a19d-4389426e010d)

Not sure why it only occurs for that Programming Night Event.

**Comment by martinheidegger** [comment]
@coliff vite uses a mixed "SSR" and live data loading concept I think. The build process for the files currently builds all event pages as html sites but when the site is loaded it also seems to go to the /public folder to load the latest events which is a problem if they are out of sync but what happens at my computer is that sometimes it shows briefly the new event list before deciding to show an outdated Event list. An extremely weird behavior (which is not same as in the screenshot, needs to be shown in a movie). 

I think to fix this we have three options.


1. Do not load any dynamic data in the deployed site and just keep the old data.
2. Use a different hosting system that supports dynamic urls (to have proper event urls) which I would kind of like
3. Change the build task to exclusively load the latest data from /public in the client only (no files generated during deploy). This would break current event urls and I think it may be a bad approach in general.

**Comment by kinxiel** [comment]
OK I think, I see what you mean. On the latest merge (update Nuxt to 3.4.4). For a very brief instant I see the TBA event on refreshing the page, which is weird since it was showing up normally when I tested locally before merging and also before merging.

Curious what would happen if you pushed new data.

**Comment by martinheidegger** [comment]
Astro and React fixes this issue by having a dedicated hydration function. I havn't encountered caching issues for the time being.
