### ISSUE TITLE
Menu Rendering issues

### ISSUE THREAD

**Issue by martinheidegger** [owddm/owddm.github.io#179]
The menu rendering has problems.

- It overlaps the content and, depending on the content below, it may show some content below
    <img width="816" alt="Screen Shot 2023-06-27 at 08 46 36" src="https://github.com/owddm/owddm.github.io/assets/914122/766c1282-5417-4c80-9031-a796c2d24394">
- All menu Items are twice in the HTML code which may cause maintenance issues (inconsistencies) and also problems with a11y.
- Once the mobile menu is open, it stays open even if the size changes back to desktop size:
    [screen recording](https://github.com/owddm/owddm.github.io/assets/914122/a6e0306d-701b-455e-bbff-4710da5d332a)
- The content switches to the mobile menu unnecessarily early
    [screen recording](https://github.com/owddm/owddm.github.io/assets/914122/96687425-bf6b-4b7b-b71d-1e3938fe5e1f)
- The button area of the menu items is small and it doesn't contain a `hover` effect
    [screen recording](https://github.com/owddm/owddm.github.io/assets/914122/759a8804-7cf5-4432-9913-eafdbd6a3dd5)

**Comment by kinxiel** [comment]
Todos:

- [x] Fix for displays 320 px or smaller
- [ ] Check insets
- [ ] Accessibility of hamburger

**Comment by martinheidegger** [comment]
Closing issue for now, it seems fixed as far as the issue is concerned
