### ISSUE TITLE
Social Media icons appear doubled only on the deployed version

### ISSUE THREAD

**Issue by kinxiel** [owddm/owddm.github.io#187]
Not sure why, but issue only occurs in the deployed Github pages version.

![image](https://github.com/owddm/owddm.github.io/assets/11483654/16ed3209-ae90-49b0-ae47-dcac87b53d63)

Both the Dev and Build versions do not show this problem.

**Comment by kinxiel** [comment]
Although not the exact source of the problem, it should be fixed by the PR branch addressing https://github.com/owddm/owddm.github.io/issues/179

**Comment by kinxiel** [comment]
Seems like it's a different issue, still getting duplicate icons in production. Might be a problem with the Github pages? Works fine locally after building.

**Comment by martinheidegger** [comment]
Fixed in a commit a long time ago. 😅
