### ISSUE TITLE
Mobile nav menu remains open after clicking 'join' button

### ISSUE THREAD

**Issue by AndrewZamora** [owddm/owddm.github.io#269]
When the mobile navigation menu is open and the 'Join' button in the header is clicked, the page correctly navigates to the 'Join' page. However, the mobile navigation menu remains open, obscuring the content of the 'Join' page. Happy to make a pull request if that is okay.

Also, this might be a separate issue but should the 'Join' button be removed while on the 'Join' page?

**Comment by martinheidegger** [comment]
> When the mobile navigation menu is open and the 'Join' button in the header is clicked, the page correctly navigates to the 'Join' page. However, the mobile navigation menu remains open, obscuring the content of the 'Join' page. Happy to make a pull request if that is okay.

Nice bug, happy to okay a PR for it!

> Also, this might be a separate issue but should the 'Join' button be removed while on the 'Join' page?

It seems to me like it makes sense to keep the navigation even if you navigated to the location. Adding a style that highlights that the menu point is selected might be a good idea.
